version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: bank_postgres
    restart: always
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: card-app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bank_db
      SPRING_DATASOURCE_USERNAME: bank_user
      SPRING_DATASOURCE_PASSWORD: bank_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_LIQUIBASE_ENABLED: true

volumes:
  postgres_data:
