spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bank_db
    username: bank_user
    password: bank_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db-changelog-master.yaml

  logging:
    level:
      root: DEBUG
      org.springframework.security: DEBUG
      org.springframework.security.web: DEBUG
      org.springframework.security.authentication: DEBUG
      com.example.card_app: DEBUG
      org.springframework.web: DEBUG
      org.springframework.web.filter: DEBUG

